<script setup lang="ts">
import {onMounted,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,post,put} from '../api/client'
import type {Snapshot} from '../api/types'
import {useAuthStore} from '../stores/auth'
const auth=useAuthStore(),files=ref<string[]>([]),selected=ref(''),content=ref(''),history=ref<Snapshot[]>([]),reason=ref(''),loading=ref(false),validation=ref('尚未校验')
async function open(name:string){selected.value=name;const data=await api<{content:string}>(`/api/config/file?path=${encodeURIComponent(name)}`);content.value=data.content;history.value=await api(`/api/config/history?path=${encodeURIComponent(name)}`);validation.value='尚未校验'}
async function validate(){try{await post('/api/config/validate',{path:selected.value,content:content.value});validation.value='校验通过';ElMessage.success('配置格式有效');return true}catch(e){validation.value=(e as Error).message;ElMessage.error(validation.value);return false}}
async function save(){if(!await validate())return;loading.value=true;try{await put('/api/config/file',{path:selected.value,content:content.value,reason:reason.value});ElMessage.success('保存成功；部分配置可能需要重启服务器生效');await open(selected.value)}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function restore(id:number){try{await ElMessageBox.confirm(`确认回滚到快照 #${id}？当前内容也会自动保存为快照。`,'确认回滚',{type:'warning'});await post('/api/config/restore',{snapshot_id:id});ElMessage.success('配置已回滚');await open(selected.value)}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
onMounted(async()=>{try{files.value=await api('/api/config/files');if(files.value.length)await open(files.value[0])}catch(e){ElMessage.error((e as Error).message)}})
</script>
<template><div class="editor-layout"><aside class="panel file-list"><div class="panel-title"><h2>白名单文件</h2></div><button v-for="file in files" :key="file" :class="{active:selected===file}" @click="open(file)">{{file}}</button></aside><section class="panel"><div class="panel-title"><h2>{{selected||'选择配置文件'}}</h2><div v-if="auth.canWrite" class="actions"><el-button @click="validate">校验</el-button><el-button type="success" :loading="loading" :disabled="!selected" @click="save">保存并创建快照</el-button></div><el-tag v-else type="info">只读</el-tag></div><textarea v-model="content" class="editor" spellcheck="false" :readonly="!auth.canWrite"/><el-input v-if="auth.canWrite" v-model="reason" placeholder="变更原因（建议填写）" style="margin-top:12px"/></section><aside class="panel"><div class="panel-title"><h2>校验结果</h2></div><p :style="{color:validation==='校验通过'?'var(--green)':'var(--muted)'}">{{validation}}</p><div class="panel-title" style="margin-top:28px"><h2>历史快照</h2></div><div v-if="!history.length" class="empty">暂无快照</div><div v-for="item in history" :key="item.id" class="history-item"><strong>#{{item.id}}</strong> · {{item.reason||'未填写原因'}}<time>{{new Date(item.created_at).toLocaleString()}}</time><el-button v-if="auth.canWrite" link type="warning" @click="restore(item.id)">回滚到此版本</el-button></div></aside></div></template>
