<script setup lang="ts">
import {nextTick,onMounted,onUnmounted,ref} from 'vue'
import {ElMessage} from 'element-plus'
import {api} from '../api/client'
import type {LogEntry} from '../api/types'
import {useAuthStore} from '../stores/auth'
const auth=useAuthStore(),logs=ref<LogEntry[]>([]),command=ref(''),connected=ref(false),paused=ref(false),autoScroll=ref(true),level=ref('all'),terminal=ref<HTMLElement>();let ws:WebSocket|undefined,retry=0,closed=false
function connect(){const scheme=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${scheme}://${location.host}/api/logs/stream`);ws.onopen=()=>{connected.value=true;retry=0};ws.onclose=()=>{connected.value=false;if(!closed)window.setTimeout(connect,Math.min(1000*2**retry++,10000))};ws.onmessage=async e=>{const msg=JSON.parse(e.data);if(msg.type==='log'&&!paused.value){logs.value.push(msg.data);if(logs.value.length>2000)logs.value.splice(0,500);if(autoScroll.value){await nextTick();terminal.value?.scrollTo({top:terminal.value.scrollHeight})}}}}
function send(){const value=command.value.trim();if(!value)return;if(!ws||ws.readyState!==WebSocket.OPEN){ElMessage.error('控制台尚未连接');return};ws.send(JSON.stringify({type:'command',data:{command:value}}));command.value=''}
onMounted(async()=>{try{logs.value=(await api<LogEntry[]>('/api/logs?limit=300')).reverse()}catch(e){ElMessage.error((e as Error).message)}connect()});onUnmounted(()=>{closed=true;ws?.close()})
</script>
<template><section class="panel"><div class="panel-title"><h2>实时输出</h2><span class="status" :class="connected?'running':'crashed'">{{connected?'CONNECTED':'DISCONNECTED'}}</span></div><div class="toolbar"><el-select v-model="level" style="width:130px"><el-option label="全部级别" value="all"/><el-option label="Info" value="info"/><el-option label="Warn" value="warn"/><el-option label="Error" value="error"/></el-select><el-switch v-model="autoScroll" active-text="自动滚动"/><el-switch v-model="paused" active-text="暂停接收"/><el-button @click="logs=[]">清空视图</el-button></div><div ref="terminal" class="terminal"><div v-for="(line,i) in logs.filter(x=>level==='all'||x.level===level)" :key="line.id||i" class="log-line" :class="line.level"><span class="time">{{new Date(line.created_at).toLocaleTimeString()}}</span><span class="level">{{line.level.toUpperCase()}}</span><span>{{line.message}}</span></div></div><div class="command-row"><el-input v-model="command" :disabled="!connected||!auth.canWrite" :placeholder="auth.canWrite?'输入 Minecraft 命令，例如 list 或 say hello':'当前账户只有只读权限'" @keyup.enter="send"><template #prepend>&gt;</template></el-input><el-button type="success" :disabled="!auth.canWrite||!connected||!command.trim()" @click="send">发送</el-button></div></section></template>
