<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api} from '../api/client'
import type {LogEntry,MetricsSummary} from '../api/types'
import {useServerStore} from '../stores/server'
import {useAuthStore} from '../stores/auth'
const store=useServerStore(),auth=useAuthStore();const metrics=ref<MetricsSummary>();const errors=ref<LogEntry[]>([]);let timer=0
const bytes=(v=0)=>v>1073741824?`${(v/1073741824).toFixed(1)} GB`:`${(v/1048576).toFixed(0)} MB`;const uptime=computed(()=>{const s=store.status.uptime_seconds;return `${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`})
async function refresh(){try{await store.refresh();metrics.value=await api('/api/metrics/summary');errors.value=(await api<LogEntry[]>('/api/logs/search?q=error&limit=5'))}catch(e){ElMessage.error((e as Error).message)}}
async function act(name:'start'|'stop'|'restart'){try{if(name==='restart')await ElMessageBox.confirm('服务器将短暂离线，确认重启？','确认重启',{type:'warning'});await store.action(name);ElMessage.success('操作已完成')}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
onMounted(()=>{refresh();timer=window.setInterval(refresh,5000)});onUnmounted(()=>clearInterval(timer))
</script>
<template><div class="grid grid-4"><div class="metric-card"><small>SERVER STATUS</small><strong><span class="status" :class="store.status.state">{{store.status.state}}</span></strong><em>PID {{store.status.pid||'—'}}</em></div><div class="metric-card"><small>UPTIME</small><strong>{{uptime}}</strong><em>current run</em></div><div class="metric-card"><small>PROCESS CPU</small><strong>{{metrics?.process.cpu_percent.toFixed(1)||'0.0'}}%</strong><em>bedrock_server</em></div><div class="metric-card"><small>PROCESS MEMORY</small><strong>{{bytes(metrics?.process.memory_bytes)}}</strong><em>resident set</em></div></div><div class="grid grid-2" style="margin-top:16px"><section class="panel"><div class="panel-title"><h2>服务器控制</h2><span class="status" :class="store.status.state">{{store.status.state}}</span></div><p class="muted">{{auth.canWrite?'控制本机 Bedrock Dedicated Server 进程。停止操作会先发送 Minecraft 的 stop 命令。':'当前账户为只读角色，不能控制服务器。'}}</p><div class="actions"><el-button type="success" :loading="store.loading" :disabled="!auth.canWrite||store.status.state==='running'" @click="act('start')">启动服务器</el-button><el-button :loading="store.loading" :disabled="!auth.canWrite||store.status.state!=='running'" @click="act('stop')">安全停止</el-button><el-button type="warning" plain :loading="store.loading" :disabled="!auth.canWrite||store.status.state!=='running'" @click="act('restart')">重启</el-button></div></section><section class="panel"><div class="panel-title"><h2>最近错误</h2><router-link to="/logs" class="muted">查看全部</router-link></div><div v-if="!errors.length" class="empty">没有错误日志</div><div v-for="item in errors" :key="item.id" class="history-item"><span>{{item.message}}</span><time>{{new Date(item.created_at).toLocaleString()}}</time></div></section></div></template>
