<script setup lang="ts">
import {onMounted,reactive,ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'
import {api,post,put} from '../api/client'
import type {Role,User} from '../api/types'
const users=ref<User[]>([]),loading=ref(false),create=reactive({username:'',password:'',role:'viewer' as Role})
async function load(){users.value=await api<User[]>('/api/users')}
async function add(){loading.value=true;try{await post('/api/users',create);create.username='';create.password='';create.role='viewer';ElMessage.success('用户已创建');await load()}catch(e){ElMessage.error((e as Error).message)}finally{loading.value=false}}
async function save(u:User){try{await put(`/api/users/${u.id}`,{role:u.role,disabled:u.disabled});ElMessage.success('权限已更新');await load()}catch(e){ElMessage.error((e as Error).message);await load()}}
async function reset(u:User){try{const {value}=await ElMessageBox.prompt(`为 ${u.username} 设置新密码（至少 12 个字符）`,'重置密码',{inputType:'password',inputPattern:/.{12,128}/,inputErrorMessage:'密码长度必须为 12-128 个字符'});await put(`/api/users/${u.id}/password`,{password:value});ElMessage.success('密码已重置，该用户的所有会话已退出')}catch(e){if(e!=='cancel')ElMessage.error((e as Error).message)}}
onMounted(()=>load().catch(e=>ElMessage.error(e.message)))
</script>
<template><div class="grid grid-2 user-grid"><section class="panel"><div class="panel-title"><h2>账户与角色</h2><span class="muted">{{users.length}} USERS</span></div><el-table :data="users"><el-table-column prop="username" label="用户名"/><el-table-column label="角色" width="145"><template #default="{row}"><el-select v-model="row.role" @change="save(row)"><el-option label="管理员" value="admin"/><el-option label="操作员" value="operator"/><el-option label="只读" value="viewer"/></el-select></template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-switch v-model="row.disabled" inline-prompt active-text="禁用" inactive-text="启用" @change="save(row)"/></template></el-table-column><el-table-column width="100"><template #default="{row}"><el-button link type="warning" @click="reset(row)">重置密码</el-button></template></el-table-column></el-table><p class="muted role-help">管理员：全部权限及用户管理；操作员：服务器控制、命令和配置修改；只读：状态、日志、配置和指标查看。</p></section><section class="panel"><div class="panel-title"><h2>创建用户</h2></div><el-form label-position="top" @submit.prevent="add"><el-form-item label="用户名"><el-input v-model="create.username" minlength="3" maxlength="64"/></el-form-item><el-form-item label="初始密码"><el-input v-model="create.password" type="password" show-password minlength="12" maxlength="128"/></el-form-item><el-form-item label="角色"><el-select v-model="create.role" style="width:100%"><el-option label="管理员" value="admin"/><el-option label="操作员" value="operator"/><el-option label="只读" value="viewer"/></el-select></el-form-item><el-button type="success" native-type="submit" :loading="loading" :disabled="create.username.length<3||create.password.length<12">创建用户</el-button></el-form></section></div></template>
